In [ ]:
import pandas as pd
import numpy as np
import ftfy

In [28]:
data = pd.read_excel("euro_lineups euro_coaches euro_summary.xlsx")
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

,country_code,name,name_shirt,jersey_namber,position_national,position_field,position_field_detailed,country_birth,birth_date,id_match,id_player,start,year,start_position_x,start_position_y,height,id_club,weight,id_national_team
0,SRB,Blagoje Vidinić,Vidini,1,NaN,NaN,NaN,NaN,1934-06-11,4025,36774,field,1960,NaN,NaN,NaN,NaN,NaN,NaN
1,SRB,Vladimir Djurković,Durkovi,2,DEFENDER,DEFENDER,UNKNOWN,NaN,1937-11-06,4025,36735,field,1960,NaN,NaN,NaN,NaN,NaN,NaN
2,SRB,Fahrudin Jusufi,Jusufi,3,NaN,NaN,NaN,NaN,1939-12-08,4025,36723,field,1960,NaN,NaN,NaN,NaN,NaN,NaN
3,SRB,Ante Žanetić,aneti,4,NaN,NaN,NaN,NaN,1936-11-18,4025,36747,field,1960,NaN,NaN,NaN,NaN,NaN,NaN
4,SRB,Jovan Miladinović,Miladinovi,5,NaN,NaN,NaN,NaN,1939-01-30,4025,36795,field,1960,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16514,GER,Jamal Musiala,Musiala,10,MIDFIELDER,MIDFIELDER,UNKNOWN,GER,2003-02-26,2036161,250124430,field,2024,124.0,681.0,NaN,50037.0,NaN,47.0
16515,GER,Florian Wirtz,Wirtz,17,MIDFIELDER,MIDFIELDER,WINGER,GER,2003-05-03,2036161,250139445,field,2024,875.0,681.0,NaN,50109.0,NaN,47.0
16516,GER,Maximilian Mittelstädt,Mittelstdt,18,DEFENDER,DEFENDER,FULL_BACK,NaN,1997-03-18,2036161,250090766,field,2024,875.0,279.0,NaN,50107.0,NaN,47.0
16517,GER,ؤ°lkay Gündoؤںan,Gndoan,21,MIDFIELDER,MIDFIELDER,CENTRAL_MIDFIELDER,NaN,1990-10-24,2036161,250005335,field,2024,501.0,621.0,180.0,50080.0,80.0,47.0
16518,GER,Robert Andrich,Andrich,23,MIDFIELDER,MIDFIELDER,NaN,GER,1994-09-22,2036161,250055957,field,2024,294.0,473.0,NaN,50109.0,NaN,47.0

In [23]:
pd.Series(list(data["name"].str.replace(r"[^A-Za-z0-9]","",regex=True).sum())).value_counts()

pd.Series([
    c for name in data["name"].dropna().astype(str)
    for c in name
    if not c.isalnum()
    ]).value_counts()

     16803
،      716
-      191
±      175
       159
£      148
'      126
؛      108
›       94
"       64
¦       55
‡       53
‍       41
™       40
°       37
¯       36
†       22
®       22
¢       20
´       20
‰       15
…       11
«        9
»        4
Name: count, dtype: int64

In [24]:
data["name"] = data["name"].apply(ftfy.fix_text)

In [20]:
df = pd.DataFrame({
    'Symbols:': ['«','„','¦','–',"'",'°','¯','†','®','¨','¢','´','‰',"أ©","›","أ¨","أª","أ«","أ¡","أ³","أ­","أº","أ±","أ¼","أ¶","أ¤","أŸ","أ¸","أ¥","أ§","أŒ","œ","إ½","إ¾","إ،","ؤچ","ؤ‡","إ‘", "‘", "‚","إ±","إ™","أ°","أ¾","–","‘","’"],
    'Letters:': ['ë','ń','æ','Ö',"$",'İ','ů','Ć','î','è','Ţ','ô','É',"é","é", "è", "ê", "ë", "á", "ó", "í", "ú", "ñ", "ü", "ö", "ä", "ß", "ø", "å", "ç", "Œ", "œ", "Ž", "ž", "š", "č", "ć", "ő", "ő", "ő", "ű", "ř", "ğ", "ş", "-", "'", "'"]
})

mapping = dict(zip(df['Symbols:'], df['Letters:']))

mapping.update({
    "إ ": "Š",
    "إ ": "Š",
})

df

   Symbols: Letters:
0         «        ë
1         „        ń
2         ¦        æ
3         –        Ö
4         '        $
5         °        İ
6         ¯        ů
7         †        Ć
8         ®        î
9         ¨        è
10        ¢        Ţ
11        ´        ô
12        ‰        É
13       أ©        é
14        ›        é
15       أ¨        è
16       أª        ê
17       أ«        ë
18       أ¡        á
19       أ³        ó
20       أ­        í
21       أº        ú
22       أ±        ñ
23       أ¼        ü
24       أ¶        ö
25       أ¤        ä
26       أŸ        ß
27       أ¸        ø
28       أ¥        å
29       أ§        ç
30       أŒ        Œ
31        œ        œ
32       إ½        Ž
33       إ¾        ž
34       إ،        š
35       ؤچ        č
36       ؤ‡        ć
37       إ‘        ő
38        ‘        ő
39        ‚        ő
40       إ±        ű
41       إ™        ř
42       أ°        ğ
43       أ¾        ş
44        –        -
45        ‘        '
46        ’        '

In [13]:
cols = ['name', 'name_shirt']

for col in cols:
    data[col] = data[col].astype(str)
    for k, v in mapping.items():
        data[col] = data[col].str.replace(k, v, regex=False)

In [26]:
data['name_shirt'] = data['name_shirt'].astype(str)\
.str.encode('latin1', errors='ignore')\
.str.decode('utf-8', errors='ignore')